import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/app_state.provider.dart';
import '../models/coupon_profile.dart';
import '../models/site.dart';

class ProfilesScreen extends StatefulWidget {
  const ProfilesScreen({super.key});

  @override
  State<ProfilesScreen> createState() => _ProfilesScreenState();
}

class _ProfilesScreenState extends State<ProfilesScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _validityController = TextEditingController(text: '30');
  final _retailPriceController = TextEditingController();
  final _promoPriceController = TextEditingController();
  final _costPriceController = TextEditingController();
  final _descController = TextEditingController();

  bool _isAdding = false;

  @override
  void dispose() {
    _nameController.dispose();
    _validityController.dispose();
    _retailPriceController.dispose();
    _promoPriceController.dispose();
    _costPriceController.dispose();
    _descController.dispose();
    super.dispose();
  }

  void _handleAddProfile(AppStateProvider appState) async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isAdding = true);

    final newProfile = CouponProfile(
      id: '', // Generated by SupabaseService
      name: _nameController.text.trim(),
      validityDays: int.parse(_validityController.text.trim()),
      price: double.parse(_retailPriceController.text.trim()),
      salePrice: double.parse(_promoPriceController.text.trim()),
      costPrice: double.parse(_costPriceController.text.trim()),
      description: _descController.text.trim(),
      status: 'Active',
    );

    try {
      await appState.addCouponProfile(newProfile);
      _nameController.clear();
      _validityController.text = '30';
      _retailPriceController.clear();
      _promoPriceController.clear();
      _costPriceController.clear();
      _descController.clear();
    } catch (e) {
      // Handled by toast
    } finally {
      setState(() => _isAdding = false);
    }
  }

  void _confirmDeleteProfile(BuildContext context, AppStateProvider appState, CouponProfile profile) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Profile', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
        content: Text('Are you sure you want to delete profile "${profile.name}"? Active coupons using this reference will lose their template. This cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: Colors.redAccent, foregroundColor: Colors.white),
            onPressed: () async {
              Navigator.of(context).pop();
              await appState.deleteCouponProfile(profile.id);
            },
            child: const Text('Delete'),
          )
        ],
      ),
    );
  }

  Widget _buildProfileCard(BuildContext context, AppStateProvider appState, CouponProfile p, List<String> siteNames) {
    return Card(
      elevation: 0,
      margin: const EdgeInsets.only(bottom: 12),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(color: Colors.grey.withOpacity(0.15)),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    const Icon(Icons.layers_outlined, size: 16, color: Color(0xFF6366F1)),
                    const SizedBox(width: 6),
                    Text(p.name, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold)),
                  ],
                ),
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 1.5),
                      decoration: BoxDecoration(
                        color: siteNames.isNotEmpty ? Colors.green.withOpacity(0.08) : Colors.amber.withOpacity(0.08),
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: Text(
                        siteNames.isNotEmpty ? 'Active' : 'Unassigned',
                        style: TextStyle(
                          color: siteNames.isNotEmpty ? Colors.green : Colors.amber[800],
                          fontSize: 9,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    const SizedBox(width: 6),
                    IconButton(
                      icon: const Icon(Icons.delete_outline, size: 16, color: Colors.redAccent),
                      onPressed: () => _confirmDeleteProfile(context, appState, p),
                      constraints: const BoxConstraints(),
                      padding: EdgeInsets.zero,
                    )
                  ],
                )
              ],
            ),
            const SizedBox(height: 6),
            Text(
              p.description.isNotEmpty ? p.description : 'No description provided.',
              style: TextStyle(fontSize: 11.5, color: Colors.grey[600], height: 1.4),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                const Icon(Icons.calendar_today_outlined, size: 12, color: Colors.grey),
                const SizedBox(width: 4),
                Text('Validity: ', style: TextStyle(fontSize: 11, color: Colors.grey[600])),
                Text('${p.validityDays} Days', style: const TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
              ],
            ),
            if (siteNames.isNotEmpty) ...[
              const SizedBox(height: 8),
              Wrap(
                spacing: 4,
                runSpacing: 4,
                children: siteNames.map((sName) => Container(
                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                      decoration: BoxDecoration(color: Colors.blue.withOpacity(0.06), borderRadius: BorderRadius.circular(4)),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(Icons.map_outlined, size: 10, color: Colors.blue),
                          const SizedBox(width: 3),
                          Text(sName, style: const TextStyle(fontSize: 9.5, color: Colors.blue, fontWeight: FontWeight.w600)),
                        ],
                      ),
                    )).toList(),
              ),
            ],
            const Divider(height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Retail Price', style: TextStyle(fontSize: 9, color: Colors.grey)),
                    Text('${p.price.toInt()} AED', style: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.bold)),
                  ],
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Promo Price', style: TextStyle(fontSize: 9, color: Colors.grey)),
                    Text('${p.salePrice.toInt()} AED', style: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.bold, color: Colors.green)),
                  ],
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Unit Cost', style: TextStyle(fontSize: 9, color: Colors.grey)),
                    Text('${p.costPrice.toInt()} AED', style: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.bold)),
                  ],
                ),
              ],
            )
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppStateProvider>(context);

    // Group profiles
    final List<Map<String, dynamic>> assignedProfiles = [];
    final List<CouponProfile> unassignedProfiles = [];

    for (final p in appState.couponProfiles) {
      final assignedSiteIds = appState.sitePrices
          .where((sp) => sp['profileId'] == p.id)
          .map((sp) => sp['siteId'] as String)
          .toSet();
      final List<String> siteNames = appState.sites
          .where((s) => assignedSiteIds.contains(s.id))
          .map((s) => s.name)
          .toList();

      if (siteNames.isNotEmpty) {
        assignedProfiles.add({
          'profile': p,
          'siteNames': siteNames,
        });
      } else {
        unassignedProfiles.add(p);
      }
    }

    // Dynamic grouping by site name
    final Map<String, List<CouponProfile>> siteGroupedMap = {};
    for (final s in appState.sites) {
      final assignedProfIds = appState.sitePrices
          .where((sp) => sp['siteId'] == s.id)
          .map((sp) => sp['profileId'] as String)
          .toSet();
      final List<CouponProfile> profiles = appState.couponProfiles
          .where((p) => assignedProfIds.contains(p.id))
          .toList();

      if (profiles.isNotEmpty) {
        siteGroupedMap[s.name] = profiles;
      }
    }

    return Scaffold(
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Create Profile Form
            Card(
              elevation: 0,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
                side: BorderSide(color: Colors.grey.withOpacity(0.15)),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Create Package Profile', style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _nameController,
                        decoration: const InputDecoration(labelText: 'Profile Name *', hintText: 'e.g. 15 Days Unlimited'),
                        validator: (val) => (val == null || val.trim().isEmpty) ? 'Name required' : null,
                      ),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _validityController,
                        keyboardType: TextInputType.number,
                        decoration: const InputDecoration(labelText: 'Validity (Days) *', hintText: '30'),
                        validator: (val) {
                          if (val == null || val.trim().isEmpty) return 'Validity required';
                          if (int.tryParse(val) == null) return 'Enter valid integer';
                          return null;
                        },
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: TextFormField(
                              controller: _retailPriceController,
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Retail (AED) *', contentPadding: EdgeInsets.all(10)),
                              validator: (val) => (val == null || val.trim().isEmpty) ? 'Required' : null,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: TextFormField(
                              controller: _promoPriceController,
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Promo (AED) *', contentPadding: EdgeInsets.all(10)),
                              validator: (val) => (val == null || val.trim().isEmpty) ? 'Required' : null,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: TextFormField(
                              controller: _costPriceController,
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Cost (AED) *', contentPadding: EdgeInsets.all(10)),
                              validator: (val) => (val == null || val.trim().isEmpty) ? 'Required' : null,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _descController,
                        maxLines: 2,
                        decoration: const InputDecoration(labelText: 'Description', hintText: 'Short plan summary...'),
                      ),
                      const SizedBox(height: 16),
                      ElevatedButton.icon(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF6366F1),
                          foregroundColor: Colors.white,
                          minimumSize: const Size(double.infinity, 45),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                        ),
                        onPressed: _isAdding ? null : () => _handleAddProfile(appState),
                        icon: _isAdding
                            ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, valueColor: AlwaysStoppedAnimation<Color>(Colors.white)))
                            : const Icon(Icons.add, size: 16),
                        label: const Text('Add Profile', style: TextStyle(fontWeight: FontWeight.bold)),
                      ),
                    ],
                  ),
                ),
              ),
            ),

            const SizedBox(height: 24),

            // Profile listing grouped by site
            ...siteGroupedMap.keys.map((siteName) {
              final profiles = siteGroupedMap[siteName]!;
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: Row(
                      children: [
                        const Icon(Icons.business, size: 16, color: Colors.blue),
                        const SizedBox(width: 6),
                        Text(siteName, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold)),
                      ],
                    ),
                  ),
                  ...profiles.map((p) {
                    final assignedSiteIds = appState.sitePrices
                        .where((sp) => sp['profileId'] == p.id)
                        .map((sp) => sp['siteId'] as String)
                        .toSet();
                    final List<String> siteNames = appState.sites
                        .where((s) => assignedSiteIds.contains(s.id))
                        .map((s) => s.name)
                        .toList();
                    return _buildProfileCard(context, appState, p, siteNames);
                  }).toList(),
                ],
              );
            }).toList(),

            // Unassigned profiles
            if (unassignedProfiles.isNotEmpty) ...[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 8.0),
                child: Row(
                  children: const [
                    Icon(Icons.layers_clear_outlined, size: 16, color: Colors.grey),
                    SizedBox(width: 6),
                    Text('Unassigned Profiles', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Colors.grey)),
                  ],
                ),
              ),
              ...unassignedProfiles.map((p) => _buildProfileCard(context, appState, p, [])).toList(),
            ],

            if (appState.couponProfiles.isEmpty)
              const Center(
                child: Padding(
                  padding: EdgeInsets.symmetric(vertical: 32.0),
                  child: Text('No profiles configured yet. Add one above.', style: TextStyle(color: Colors.grey)),
                ),
              ),
          ],
        ),
      ),
    );
  }
}
