import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/app_state.provider.dart';
import '../models/user.dart';
import '../models/site.dart';

class UsersScreen extends StatefulWidget {
  const UsersScreen({super.key});

  @override
  State<UsersScreen> createState() => _UsersScreenState();
}

class _UsersScreenState extends State<UsersScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  String _selectedRole = 'Staff';
  final List<String> _selectedSites = [];

  bool _isCreating = false;

  @override
  void dispose() {
    _nameController.dispose();
    _usernameController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  void _handleSiteCheckbox(String siteId, bool checked) {
    setState(() {
      if (checked) {
        _selectedSites.add(siteId);
      } else {
        _selectedSites.remove(siteId);
      }
    });
  }

  void _handleCreateUser(AppStateProvider appState) async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isCreating = true);

    final newUser = AppUser(
      id: '', // Generated by SupabaseService
      username: _usernameController.text.trim(),
      password: _passwordController.text.trim(),
      role: _selectedRole,
      name: _nameController.text.trim(),
      twoFAEnabled: false,
    );

    try {
      await appState.addUser(
        newUser,
        _selectedRole == 'Admin' ? [] : _selectedSites,
      );
      _nameController.clear();
      _usernameController.clear();
      _passwordController.clear();
      setState(() {
        _selectedRole = 'Staff';
        _selectedSites.clear();
      });
    } catch (e) {
      // handled by provider toast
    } finally {
      setState(() => _isCreating = false);
    }
  }

  void _handleResetPassword(AppStateProvider appState, AppUser u) {
    appState.showToast('Password for user ${u.name} reset to default: "ChangeMe2026!"');
  }

  void _confirmDeleteUser(BuildContext context, AppStateProvider appState, AppUser u) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete User Account', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
        content: Text('Are you sure you want to delete user "${u.name}"? This will disable their access and delete their profile. This cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: Colors.redAccent, foregroundColor: Colors.white),
            onPressed: () async {
              Navigator.of(context).pop();
              await appState.deleteUser(u.id);
            },
            child: const Text('Delete'),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppStateProvider>(context);
    final usersList = appState.users;
    final sitesList = appState.sites;

    return Scaffold(
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Create User account form
            Card(
              elevation: 0,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
                side: BorderSide(color: Colors.grey.withOpacity(0.15)),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Create User Account', style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _nameController,
                        decoration: const InputDecoration(labelText: 'Full Name *', hintText: 'e.g. John Doe'),
                        validator: (val) => (val == null || val.trim().isEmpty) ? 'Full Name required' : null,
                      ),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _usernameController,
                        decoration: const InputDecoration(labelText: 'Username *', hintText: 'e.g. john_doe'),
                        validator: (val) => (val == null || val.trim().isEmpty) ? 'Username required' : null,
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: DropdownButtonFormField<String>(
                              decoration: const InputDecoration(labelText: 'System Role *', contentPadding: EdgeInsets.all(10)),
                              value: _selectedRole,
                              items: const [
                                DropdownMenuItem(value: 'Admin', child: Text('Admin')),
                                DropdownMenuItem(value: 'Owner', child: Text('Owner')),
                                DropdownMenuItem(value: 'Manager', child: Text('Manager')),
                                DropdownMenuItem(value: 'Super Staff', child: Text('Super Staff')),
                                DropdownMenuItem(value: 'Staff', child: Text('Staff')),
                                DropdownMenuItem(value: 'Accountant', child: Text('Accountant')),
                              ],
                              onChanged: (val) {
                                if (val != null) setState(() => _selectedRole = val);
                              },
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: TextFormField(
                              controller: _passwordController,
                              obscureText: true,
                              decoration: const InputDecoration(labelText: 'Password *', contentPadding: EdgeInsets.all(10)),
                              validator: (val) => (val == null || val.trim().isEmpty) ? 'Password required' : null,
                            ),
                          )
                        ],
                      ),

                      // Checkboxes for site mappings
                      if (_selectedRole != 'Admin' && sitesList.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        const Text('Assigned Site Scope(s)', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.grey)),
                        const SizedBox(height: 6),
                        ...sitesList.map((site) => CheckboxListTile(
                              dense: true,
                              contentPadding: EdgeInsets.zero,
                              title: Text(site.name, style: const TextStyle(fontSize: 12.5)),
                              value: _selectedSites.contains(site.id),
                              onChanged: (val) => _handleSiteCheckbox(site.id, val ?? false),
                            )),
                      ],

                      const SizedBox(height: 16),
                      ElevatedButton.icon(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF6366F1),
                          foregroundColor: Colors.white,
                          minimumSize: const Size(double.infinity, 45),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                        ),
                        onPressed: _isCreating ? null : () => _handleCreateUser(appState),
                        icon: _isCreating
                            ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, valueColor: AlwaysStoppedAnimation<Color>(Colors.white)))
                            : const Icon(Icons.add, size: 16),
                        label: const Text('Create User', style: TextStyle(fontWeight: FontWeight.bold)),
                      ),
                    ],
                  ),
                ),
              ),
            ),

            const SizedBox(height: 24),
            const Text(
              'Registered System Accounts',
              style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),

            if (usersList.isEmpty)
              const Center(
                child: Padding(
                  padding: EdgeInsets.symmetric(vertical: 32.0),
                  child: Text('No users found.', style: TextStyle(color: Colors.grey)),
                ),
              )
            else
              ...usersList.map((u) {
                final assignedSiteNames = appState.userSites
                    .where((us) => us['userId'] == u.id)
                    .map((us) => appState.sites.firstWhere((s) => s.id == us['siteId'], orElse: () => Site(id: '', name: 'Unk', location: '', status: '', smsEnabled: false)).name)
                    .where((name) => name != 'Unk')
                    .join(', ');

                return Card(
                  elevation: 0,
                  margin: const EdgeInsets.only(bottom: 12),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                    side: BorderSide(color: Colors.grey.withOpacity(0.15)),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(14.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(u.name, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold)),
                                const SizedBox(height: 2),
                                Text('@${u.username}', style: TextStyle(fontSize: 11, color: Colors.grey[600])),
                              ],
                            ),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                              decoration: BoxDecoration(
                                color: u.role == 'Admin' 
                                    ? Colors.red.withOpacity(0.08) 
                                    : u.role == 'Accountant'
                                        ? Colors.purple.withOpacity(0.08)
                                        : Colors.blue.withOpacity(0.08),
                                borderRadius: BorderRadius.circular(6),
                              ),
                              child: Text(
                                u.role,
                                style: TextStyle(
                                  fontSize: 9.5,
                                  fontWeight: FontWeight.bold,
                                  color: u.role == 'Admin' 
                                      ? Colors.red 
                                      : u.role == 'Accountant'
                                          ? Colors.purple
                                          : Colors.blue,
                                ),
                              ),
                            )
                          ],
                        ),
                        const Divider(height: 20),
                        Row(
                          children: [
                            const Icon(Icons.storefront_outlined, size: 13, color: Colors.grey),
                            const SizedBox(width: 4),
                            Expanded(
                              child: Text(
                                u.role == 'Admin' ? 'Global Access' : (assignedSiteNames.isNotEmpty ? assignedSiteNames : 'None'),
                                style: const TextStyle(fontSize: 11.5),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 4),
                        Row(
                          children: [
                            const Icon(Icons.security_outlined, size: 13, color: Colors.grey),
                            const SizedBox(width: 4),
                            Text('2FA: ', style: TextStyle(fontSize: 11.5, color: Colors.grey[600])),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 1.5),
                              decoration: BoxDecoration(
                                color: u.twoFAEnabled ? Colors.green.withOpacity(0.08) : Colors.grey.withOpacity(0.12),
                                borderRadius: BorderRadius.circular(4),
                              ),
                              child: Text(
                                u.twoFAEnabled ? 'Enabled' : 'Disabled',
                                style: TextStyle(
                                  color: u.twoFAEnabled ? Colors.green : Colors.grey[700],
                                  fontSize: 8.5,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            )
                          ],
                        ),
                        const Divider(height: 20),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            ElevatedButton.icon(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.transparent,
                                foregroundColor: const Color(0xFF6366F1),
                                elevation: 0,
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                minimumSize: const Size(60, 24),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4),
                                  side: const BorderSide(color: Color(0xFF6366F1), width: 1),
                                ),
                              ),
                              icon: const Icon(Icons.vpn_key_outlined, size: 12),
                              label: const Text('Reset PW', style: TextStyle(fontSize: 10.5, fontWeight: FontWeight.bold)),
                              onPressed: () => _handleResetPassword(appState, u),
                            ),
                            if (u.id != 'u-sysadmin') ...[
                              const SizedBox(width: 8),
                              IconButton(
                                constraints: const BoxConstraints(),
                                padding: const EdgeInsets.all(4),
                                icon: const Icon(Icons.delete_outline, color: Colors.redAccent, size: 18),
                                onPressed: () => _confirmDeleteUser(context, appState, u),
                              )
                            ]
                          ],
                        ),
                      ],
                    ),
                  ),
                );
              }).toList(),
          ],
        ),
      ),
    );
  }
}
